listener {
    timeout = 1740
    on-timeout = noctalia msg session lock
}

listener {
    timeout = 1800
    on-timeout = hyprctl dispatch 'hl.dsp.dpms("off")'; asusctl leds set off
    on-resume = hyprctl dispatch 'hl.dsp.dpms("on")'; asusctl leds set high
}
