-- Generated by Noctalia

primary = "rgb(58a6ff)"
surface = "rgb(010409)"
secondary = "rgb(bc8cff)"
error = "rgb(f85149)"
on_primary = "rgb(010409)"

hl.config({
	general = {
		col = {
			active_border = primary,
			inactive_border = surface,
		},
	},

	group = {
		col = {
			border_active = secondary,
			border_inactive = surface,
			border_locked_active = error,
			border_locked_inactive = surface,
		},

		groupbar = {
			col = {
				active = secondary,
				inactive = surface,
				locked_active = error,
				locked_inactive = surface,
			},
		},
	},
})
