#!/bin/bash
CONF="/etc/sddm.conf.d/zz-gaming-session.conf"
case "$1" in
  gaming)
    cat > "$CONF" <<- EOC
[Autologin]
User=mindset
Session=gamescope-session-steam-nm
Relogin=true
EOC
    echo "Session set to: gaming mode"
    ;;
  desktop)
    cat > "$CONF" <<- EOC
[Autologin]
User=mindset
Session=hyprland
Relogin=true
EOC
    echo "Session set to: desktop mode"
    ;;
  *)
    echo "Usage: $0 {gaming|desktop}" >&2
    exit 1
    ;;
esac
